"use client";
import {useEffect,useState} from "react";
const whatsapp="https://wa.me/5594991015005";
const pillars=[
  ["01","Estratégia médica","Emagrecimento feminino conduzido com avaliação clínica, evidências e metas possíveis."],
  ["02","Identidade Magra","Um caminho para reprogramar hábitos, mente e metabolismo sem guerra com a balança."],
  ["03","Nutrição na vida real","Escolhas sustentáveis que respeitam sua rotina, preferências e contexto familiar."],
  ["04","Força e movimento","Atividade física como ferramenta de saúde, autonomia e manutenção de resultados."],
];
export default function Home(){const[open,setOpen]=useState(false);useEffect(()=>{const a=document.querySelectorAll<HTMLElement>("[data-r]");const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("on")),{threshold:.12});a.forEach(x=>o.observe(x));return()=>o.disconnect()},[]);return <main>
<header><a className="logo" href="#inicio"><img src="/identidade-magra-logo.png" alt="Identidade Magra"/></a><button onClick={()=>setOpen(!open)}>{open?"Fechar":"Menu"}<i/></button><nav className={open?"open":""}><a href="#metodo">Método</a><a href="#doutora">Dra. Gabriela</a><a href="#jornada">Jornada</a><a href="#contato">Contato</a></nav><a className="cta" href={whatsapp} target="_blank">Agendar consulta ↗</a></header>
<section className="hero" id="inicio"><div className="copy"><p className="eye"><i/> Emagrecimento feminino baseado em evidências</p><h1>Não é sobre<br/><em>perder peso.</em><br/>É sobre se<br/><span>reencontrar.</span></h1><p>Estratégias médicas para transformar corpo, mente e rotina com consciência, equilíbrio e resultados sustentáveis.</p><div className="actions"><a href={whatsapp} target="_blank">Agende sua consulta <b>↗</b></a><a href="#metodo">Conheça o método ↓</a></div></div><div className="doctor"><div className="shape"/><img src="/dra-gabriela-meira.jpg" alt="Dra. Gabriela Meira"/><span>CRM 12.218 · RQE 7.126</span></div><small>SAÚDE · CIÊNCIA · AUTONOMIA</small></section>
<section className="manifest section" id="metodo"><p className="eye" data-r><i/> Uma nova identidade</p><div><h2 data-r>Emagrecer é mudar<br/><em>a forma de viver.</em></h2><p data-r>O método Identidade Magra integra medicina, comportamento, alimentação e movimento para construir uma relação mais leve e duradoura com o próprio corpo.</p></div><div className="pillars">{pillars.map(([n,t,p])=><article key={n} data-r><span>{n}</span><h3>{t}</h3><p>{p}</p><a href={whatsapp} target="_blank">↗</a></article>)}</div></section>
<section className="lifestyle"><div className="photo"><img src="/pexels-healthy-food.jpg" alt="Mulher desfrutando uma alimentação equilibrada"/></div><div className="text section" data-r><p className="eye"><i/> Sem extremos</p><h2>Comida de verdade.<br/><em>Vida de verdade.</em></h2><p>Sem cardápios impossíveis ou culpa. O plano precisa funcionar na sua rotina para que o resultado permaneça.</p><a href={whatsapp} target="_blank">Quero começar <b>↗</b></a></div></section>
<section className="about section" id="doutora"><div data-r><p className="eye"><i/> Quem caminha com você</p><h2>Dra. Gabriela<br/><em>Meira.</em></h2><p>Médica de Família, pós-graduada em Nutrologia da Obesidade e Sarcopenia, com certificação em ferramentas de estilo de vida pela Harvard Medical School.</p><p>Há mais de oito anos, ajuda mulheres a encontrarem leveza e consistência sem dietas restritivas — com consciência, equilíbrio e prazer.</p><a href="https://www.instagram.com/dra.gabrielameira/" target="_blank">Conhecer no Instagram ↗</a></div><div className="portrait"><img src="/dra-gabriela-meira.jpg" alt="Retrato da Dra. Gabriela Meira"/></div></section>
<section className="strength"><div className="strength-copy section" data-r><p className="eye"><i/> Corpo capaz</p><h2>Força também<br/><em>é saúde.</em></h2><p>O movimento protege massa muscular, melhora autonomia e ajuda a sustentar os resultados construídos ao longo da jornada.</p></div><img src="/pexels-strength.jpg" alt="Mulher realizando treino de força"/></section>
<section className="journey section" id="jornada"><p className="eye" data-r><i/> Seu primeiro passo</p><h2 data-r>Uma jornada feita<br/><em>para você.</em></h2><div className="steps"><article data-r><b>01</b><h3>Consulta</h3><p>História, exames, rotina e objetivos são avaliados de forma completa.</p></article><article data-r><b>02</b><h3>Estratégia</h3><p>Um plano individual reúne prioridades médicas e mudanças possíveis.</p></article><article data-r><b>03</b><h3>Acompanhamento</h3><p>Resultados e dificuldades orientam os ajustes ao longo do processo.</p></article></div></section>
<section className="contact section" id="contato"><p className="eye" data-r><i/> Presencial ou online</p><h2 data-r>Sua nova identidade<br/><em>começa agora.</em></h2><div className="contact-row"><p>Entre de primeiro na sua lista. Converse com a equipe e agende sua avaliação.</p><a href={whatsapp} target="_blank">Agendar pelo WhatsApp <b>↗</b></a></div><div className="info"><p><small>Endereço</small>Av. Potiguar, Qd. 08, Lote 18, Galeria<br/>Parque dos Carajás — Parauapebas/PA</p><p><small>Telefone</small>(94) 99101-5005</p><p><small>Instagram</small>@dra.gabrielameira</p></div></section>
<footer><img src="/identidade-magra-logo.png" alt="Identidade Magra"/><p>Clínica Saúde e Equilíbrio · Dra. Gabriela Meira</p><a href="#inicio">Voltar ao topo ↑</a><small>© 2026. Imagens complementares: Pexels.</small></footer>
</main>}
